name: catalog-counts-app
services:
- build_command: yarn build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: javiertmezac/catalog-counts-app
  name: catalog-counts-app 
